# Find the expected model names for model field in litellm_params at https://models.litellm.ai/

model_list:    
  - model_name: my-groq-model
    litellm_params:
      model: groq/qwen/qwen3.6-27b
      api_key: os.environ/GROQ_API_KEY